Update to 5.14 package
geocortex/vertigis-mobile-quickstart pull request #13
Opened 2021-08-25 20:20 UTC by jsiemensLatitudegeo

- Updated  VertiGIS.Mobile to 5.14, Xamarin.Forms to 5.0.0.2012.
- Updated layouts to include bookmarks.
- Updated UWP to 17763 min version, 18362 target version.
- Fixed android startup error.

2021-08-25 21:36 UTC, brayden-marshall approved these changes

2021-08-25 21:38 UTC, kewalker requested changes
Are you able to similarly update the android:targetSdkVersion from 29 to 30 in this repo?

2021-08-26 16:05 UTC, jsiemensLatitudegeo commented
> Are you able to similarly update the android:targetSdkVersion from 29 to 30 in this repo?

Done.

2021-08-26 16:58 UTC, kewalker approved these changes

2021-09-03 16:13 UTC, merged